GMS_proj/GMS_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import google_auth_callback
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('backoffice/', include("backoffice.urls")),
    # path('oauth2/', include('oauth2_provider_app.urls', namespace='oauth2_provider_app')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GMS_proj/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path('', views.index, name='index'),
    path('view_all_complaint_admin/', views.view_all_complaint_admin, name='view_all_complaint_admin'),
    path('login/', views.login_page, name='login'),
    path('view_complaint_reply_user/', views.view_complaint_reply_user, name='view_complaint_reply_user'),
    path('emp_profile_admin/', views.emp_profile_admin, name='emp_profile_admin'),
    path('view_emp_profile_admin/', views.view_emp_profile_admin, name='view_emp_profile_admin'),
    path('specific_complaint/', views.specific_complaint, name='specific_complaint'),
    path('complaint_user/', views.complaint_user, name='complaint_user'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
]

GMS_proj/backoffice/urls.py
app_name = 'backoffice'
from django.contrib import admin
from django.urls import path
from backoffice import views
from backoffice.views import oauth_gmail_login, oauth_callback
# from user import views as user_views
urlpatterns = [
    path('', views.navigation_admin, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('admin_registration/', views.admin_registration, name='admin_registration'),
    path('profile/', views.profile, name='profile'),
    path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    path('oauth/callback/', oauth_callback, name='oauth_callback'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('login/',views.login_page, name='login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('delete_employee', views.delete_employee, name='delete_employee'),
    # path('test/', views.test, name='test'),
    path('edit/',views.update, name='update'),
    path('complaints',views.create_complaint, name='create_complaint'),
    path('add',views.employee_add, name='employee_add'),
    
    
    
]

GMS_proj/user/urls.py
app_name = 'user'
from django.contrib import admin
from django.urls import path
from user import views
from user.views import google_auth, google_auth_callback
# from user.views import oauth_gmail_login, oauth_callback
urlpatterns = [
    path('', views.navigation, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('login/', views.login, name='login'),
    # path('change_password',views.change_password,name='change_password'),
    path('registration_user/', views.registration_user, name='registration_user'),
    #Authentication login
    # path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    
    path('edit/',views.edit_profile, name='update'),
    # path('google_login/',views.login_with_google, name='login_with_google'),
    # path('complete/gmail_login/', views.custom_login, name='complete'),
    # path('gmail/', views.login_with_gmail, name='login_with_gmail'),
    
    
    
    path('auth/google/', google_auth, name='google_auth'),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
    
]



# https://accounts.google.com/o/oauth2/auth?client_id=121742523439-s30kcv1je7lg798uen7rd4ntk1oagh39.apps.googleusercontent.com&redirect_uri=http://127.0.0.1:8000/user/complete/gmail_login/&state=PgNlIlTgE1FkGxspG8ZLTbybjrJC1H5V&response_type=code&scope=openid+email+profile

GMS_proj/user/models.py
#  This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class ComplaintMessage(models.Model):
    profile_id = models.IntegerField()
    message = models.CharField(max_length=255)
    media = models.CharField(max_length=255)
    created_at = models.DateField()
    updated_at = models.DateField()

    class Meta:
        managed = True
        db_table = 'complaint_message'


class ComplaintStatus(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'complaint_status'


class CreateComplaint(models.Model):
    profile_id = models.IntegerField()
    subject = models.CharField(max_length=40)
    message = models.CharField(max_length=1000)
    current_handler = models.CharField(max_length=35)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = True
        db_table = 'create_complaint'


class Department(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'department'


class Designation(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'designation'


class Profile(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=10)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=128)
    profile_type_id = models.IntegerField()
    designation_id = models.IntegerField()
    department_id = models.IntegerField()
    created_at = models.DateField()
    updated_at = models.DateField()
    last_login = models.DateTimeField(blank=True, null=True)
    class Meta:
        managed = True
        db_table = 'profile'


class ProfileType(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        managed = True
        db_table = 'profile_type'


class UserRegistration(models.Model):
    name = models.CharField(max_length=50)
    mobile = models.CharField(max_length=10)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=128)
    
    class Meta:
        managed = True
        db_table = 'user_registration'

GMS_proj/user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.files.storage import FileSystemStorage
from django.contrib import messages
import os
from django.http import HttpResponseBadRequest
from google.oauth2 import id_token
from google.auth.transport import requests
import requests
from google.auth.transport.requests import Request
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.hashers import make_password,check_password
from shared_model.models import Profile
from shared_model.models import ComplaintMessage
from .middleware import auth, login_checker
from shared_model.models import CreateComplaint
from django.utils import timezone
from datetime import datetime
from django.utils.crypto import get_random_string
from .exceptions import AuthCanceled
from django.urls import reverse
from django.utils import timezone
from datetime import datetime
from pytz import timezone as pytz_timezone
from django.utils.timezone import activate
from django.contrib.auth.middleware import get_user
# def emp_profile_admin(request):
#     return render(request, 'emp_profile_admin.html')
# def view_emp_profile_admin(request):
#     return render(request, 'view_emp_profile_admin.html')
#########User section############
##GOOGLE OAUTH2
def google_auth(request):
    # Redirect to Google OAuth consent screen
    google_auth_url = "https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=302465605536-96h22gh6ls1ar65m7pnasiq83gn7j1b5.apps.googleusercontent.com&redirect_uri=http://localhost:8000/auth/google/callback&scope=openid%20email%20profile"
    return redirect(google_auth_url)

def google_auth_callback(request):
    code = request.GET.get('code')
    error = request.GET.get('error')
    
    if error == 'access_denied':
        print("ERROR IS", error)
        # Handle access denied error, e.g., redirect to a specific page
        return redirect('user:login')  # Adjust URL as needed
    else:
        if code:
            try:
                # Exchange authorization code for ID token
                token_url = "https://oauth2.googleapis.com/token"
                token_data = {
                    'code': code,
                    'client_id': '302465605536-96h22gh6ls1ar65m7pnasiq83gn7j1b5.apps.googleusercontent.com',
                    'client_secret': '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',
                    'redirect_uri': 'http://localhost:8000/auth/google/callback',
                    'grant_type': 'authorization_code',
                }
                token_response = requests.post(token_url, data=token_data)
                id_token_info = id_token.verify_oauth2_token(token_response.json()['id_token'], Request())
                email=id_token_info.get('email')
                user = Profile.objects.get(email=email)
                request.session['is_logged_in'] = True
                request.session['profile_id'] = user.id
                request.session['name'] = user.name             
                if Profile.objects.filter(email=email).exists():
                    print("EMAIL EXIST IN DB",email) 
                    return redirect("user:dashboard") 
                else:
                        # Optionally, you can render an erro
                        print("Email does not exist in db",email)
                        password = get_random_string(8)
                        profile_type="User"
                        name = id_token_info.get('name')
                        user=Profile.objects.create(name=name,email=email, password=password,profile_type=profile_type)
                        print(user)
                        request.session['is_logged_in'] = True
                        return redirect("user:dashboard") 
            except Exception as e:
                print("Exception:", e)
                return HttpResponseBadRequest("Failed to authenticate with Google.")
    
        else:
            return HttpResponseBadRequest("Authorization code not provided.")
@auth
def edit_profile(request):
            p_id=request.session.get("profile_id")
            if request.method == 'POST':
                            name = request.POST.get('name','')
                            mobile = request.POST.get('mobile','')
                            email = request.POST.get('email','')
                            error_msg = []

                            response_data = {
                                'status':'',
                                'message':[],
                                'data':''
                            }
                            if name == '':
                                error_msg.append('Field Name cannot be Empty.')
                            if email == '':
                                error_msg.append('Field Email cannot be Empty.')
                            if mobile == '':
                                error_msg.append('Field Mobile Number cannot be Empty.')
                            if len(mobile) != 10:
                                error_msg.append('Mobile number must be 10 character in length.')
                            if Profile.objects.filter(email=email).exclude(id=p_id).exists():
                                error_msg.append('Email already exists. Please use a different email address.')
                            if Profile.objects.filter(mobile=mobile).exclude(id=p_id).exists():
                                error_msg.append('Mobile Number already exists. Please use a different Mobile No.')
                            profile = None
                            if p_id is not None:
                                # Fetch the existing profile if it exists
                                try:
                                    profile = Profile.objects.get(id=p_id)
                                except Profile.DoesNotExist:
                                    profile = None
                                    print('esser jkhkjh')
                            print(error_msg)
                            if(len(error_msg) == 0):
                                # Update only the fields provided in the POST request
                                print("Name:", name)
                                print("Mobile:", mobile)
                                print("Email:", email)
                                # if name:
                                #     profile.name = name
                                # if mobile:
                                #     profile.mobile = mobile
                                # if email:
                                #     profile.email = email
                                # else:
                                profile.name = name
                                profile.mobile = mobile
                                profile.email = email    
                                profile.save()     
                                print("Name:", name)
                                print("Mobile:", mobile)
                                print("Email:", email)
                                response_data['status'] = 'success'
                                response_data['message'] = ['Profile Updated Successfully.']
                                # Construct response data with updated name value
                                response_data = {
                                    'status': 'success',
                                    'message': ['Profile Updated Successfully.'],
                                    'data': {
                                        'name': name,  # Pass the updated name explicitly
                                        'mobile': mobile,
                                        'email': email
                                    }
                                }
                            else:
                                # Construct response data with error message and original data
                                response_data = {
                                    'status': 'error',
                                    'message': error_msg,
                                    'data': {
                                        'name': profile.name if profile else '',
                                        'mobile': profile.mobile if profile else '',
                                        'email': profile.email if profile else ''
                                    }
                                }
                            return render(request, 'profile.html', response_data)
            else:
                # chg_profile = get_object_or_404(Profile, id=p_id)
                # return render(request, 'profile.html', {'chg_profile': chg_profile})
                print("POST not done")
                pass
            
    

# def logout_user(request):
# #     logout(request)
# def login_with_google(request):
#     print("...............................................................")
#     profile_type="User"
#     print(type(request.user))
#     email=request.user.email
#     request.session['email_id'] = email
#     request.session['is_logged_in'] = True
#     if Profile.objects.filter(email=email).exists():
#         print("EMAIL EXIST IN DB",email) 
#         return redirect("user:dashboard") 
#     else:
#         try:
#              # Optionally, you can render an erro
#             print("Email does not exist in db",email)
#             password = get_random_string(8)
#             name = request.user.first_name + " " + request.user.last_name
#             user=Profile.objects.create(name=name,email=email, password=password,profile_type=profile_type)
#             print(user)
#             request.session['is_logged_in'] = True
#             return redirect("user:dashboard") 
#          # Your view logic here
#         except AuthCanceled as e:
#             # Handle the AuthCanceled exception

GMS_proj/user/templates/user/complaint_dashboard.html
{% extends 'navigation_user.html' %}
{% block content %}
{% load static %}
   

<h1 class="text-center">Complaint Pannel </h1>
<hr>

{% comment %} <h4>Hii: <span class="username"> {% endcomment %}
  <div class="container">
    {% for user in users %}
    {% if request.session.email_id == user.email %}
    {{ user.name }}
    {% endif %}
    {% endfor %}
</span></h4>

<a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'user:navigation' %}">
    <div class="sidebar-brand-icon rotate-n-15"></div>
</a>
<div class="container-dashboard-admin">
    <div class="row">

      <div class="col-md-6">
        <a href="{% url 'user:complaints' operation='create' %}" class="sidebar-link"> 
          <div class="box" id="employee-box1">
            <i class="fa-brands fa-creative-commons-share"></i>
            <h2>Create Complaint </h2 >
          </div>
        </a>
      </div>
  
      <div class="col-md-6">
        <a href="{% url 'user:complaints' operation='view' %}" class="sidebar-link">
          <div class="box" id="employee-box2">
            <i class="fa-regular fa-eye"></i>
            <h2>View Complaint </h2>
          </div>
        </a>
      </div>
    </div>
  </div>
  
</div>


<script>
    // Get the box elements
    const employeeBox1 = document.getElementById('employee-box1');
    const employeeBox2 = document.getElementById('employee-box2');
   

    // Add click event listeners to the boxes
    employeeBox1.addEventListener('click', function() {
        // Redirect to the specified URL when the box is clicked
        window.location.href = "{% url 'user:complaints' operation='create' %}";
    });

    employeeBox2.addEventListener('click', function() {
        // Redirect to the specified URL when the box is clicked
        window.location.href = "{% url 'user:complaints' operation='view' %}";
    });

 
</script>

{% endblock %}

GMS_proj/user/templates/user/forgot_password.html
{% extends 'navigation_user.html' %}

{% block content %}
    {% load static %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="display-6 text-center mb-4">Forgot Password</h2>
                        <form class="row g-3 needs-validation" novalidate>
                            <div class="mb-3">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                                <div class="invalid-feedback">
                                    Please enter a valid email address.
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
            <p class="text-center">Remembered your password? <a href="{% url 'user:login' %}" class="text-primary">Login</a></p>
           
        </div>
    </div>
{% endblock %}

GMS_proj/user/templates/user/login.html
{% extends 'navigation_user.html' %}
   {% block content %}
    {% load static %}
    <div class="container  ">
        <div class="row justify-content-center ">
            <div class="col-md-6">
                <div class="card ">
                    <div class="card-body ">
                        <h2 class="display-6 text-center  mb-4">Login  </h2>
                      

                        {% if message %}
                        {% for info in data %}
                        <p>{{info}}</p>
                        {% endfor %}
                        {% for msg in message %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ msg }}

                                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            </div>
                        {% endfor %}
                    {% endif %}

                        <form class="row g-3 needs-validation" method="POST" action="{% url 'user:login' %}">
                            {% csrf_token %}
                            <div class="mb-3">
                                <input type="text" class="form-control" id="name" name="email" placeholder="Username" required>
                                <div class="invalid-feedback">
                                    Please enter a valid email.
                                </div>
                            </div>
                            <div class="mb-3">
                                <input type="password" class="form-control" id="password" name="password" placeholder="Password" required>
                                <div class="invalid-feedback">
                                    Please enter a valid password.
                                </div>
                            </div>
                         <div class="oauth-buttons">
                                <a href="{% url 'user:google_auth' %}" class="gmail-button">Login with Gmail</a>
                            </div> 
                            <div class="mb-3 forgot-password">
                                <a href="{% url 'user:forgot_password' %}" class="text-danger">
                                    <i class="fa-solid fa-lock"></i><span class="p-2">Forgot Password ?</span>
                                </a>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Login</button>
                        </form>
                        
                    </div>
                    <p class="text-center ">Don't have an account? <a href="{% url 'user:registration_user' %}" class="text-warning">  Register </p>

                </div>

            </div>
        </div>
    </div>
{% endblock %}

GMS_proj/user/templates/user/navigation_user.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Layout</title>
 
    <!--Bootstrap css cnd-------->
    <link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--fontawsome----------->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Bootstrap javascript cnd--------->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    
    <!---Search Table cdn-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static '/css/my_style.css' %}">
</head>
<body>
    <div class="container-fluid p-0 d-flex h-100">
        <div id="bdSidebar"
            class="d-flex flex-column flex-shrink-0 p-3 bg-success text-white offcanvas-md offcanvas-start">
            <a href="#" class="navbar-brand">Users</a>
            <hr>
            <ul class="mynav nav nav-pills flex-column mb-auto">
                {% if not request.session.is_logged_in %}
            <li class="nav-item  mb-1">
                <a href="{% url 'user:registration_user' %}">
                    <i class="fa-regular fa-user"></i>
                    User Registration
                    <span class="notification-badge"></span>
                </a>
            </li>
                {% endif %}
               {% if request.session.is_logged_in %}
               <li class="nav-item mb-1">
                <a href="{% url 'user:dashboard' %}">
                    <i class="fa-regular fa-newspaper"></i>
                    Dashboard
                </a>
            </li>

               
                <li class="sidebar-item"> 
                    <a href="{% url 'user:complaints' operation='home' %}" class="sidebar-link"> 
                        <i class="fas fa-sign-out-alt pe-2"></i> 
                        <span class="topic">Complaint</span> 
                    </a> 
                </li> 
                  <li class="sidebar-item"> 
                    <a href="{% url 'user:profile'  %}"  class="sidebar-link"> 
                        <i class="fas fa-sign-out-alt pe-2"></i> 
                        <span class="topic">Profile</span> 
                    </a> 
                </li> 
                {% endif %}
                
                <!--Admin Section---------------------->
                <hr>
                <!--Bottom nav-->
            <div  class="mynav nav text-white ">
                
                {% if request.session.is_logged_in  %}

            <ul class="mynav nav nav-pills flex-column mb-auto">
                 <li class="nav-item  mb-1">
                    <a href="{% url 'user:logout_view' %}">
                        <i class="fa-regular fa-bookmark"></i>
                       Logout
                       
                    </a>
                </li> 
            </ul>
           
                
                {% else %} 
                
            <ul class="mynav nav nav-pills flex-column mb-auto">
                <li class="nav-item  mb-1">
                    <a href="{% url 'user:login' %}">
                        <i class="fa-regular fa-bookmark"></i>
                        Login
                        <span class="notification-badge"></span>
                    </a>
                </li>
            </ul>
     {% endif %} 
            </div>

                    <ul id="settings"
                        class="sidebar-dropdown list-unstyled collapse"
                        data-bs-parent="#sidebar"> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:login' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-in-alt pe-2"></i> 
                                <span class="topic">Login</span> 
                            </a> 
                        </li> 
                   
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="#" class="sidebar-link"> 
                                <i class="fas fa-user-plus pe-2"></i> 
                                <span class="topic">Register</span> 
                            </a> 
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:profile'%}" class="sidebar-link" > 
                                <i class="fas fa-sign-out-alt pe-2" ></i> 
                                <span class="topic">Profile</span> 
                            </a> 
                        </li> 
                       
                        {% comment %} <li class="sidebar-item"> 
                            <a href="{% url 'user:complaints' operation='specific_complaint'  %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Specific Complaint</span> 
                            </a> 
                        </li>  {% endcomment %}
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:complaints' operation='reply' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Complaint Reply</span> 
                            </a> 
                        </li> 
                        {% comment %} <li class="sidebar-item"> 
                            <a href="{% url 'user:emp_profile_admin' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Employee</span> 
                            </a> 
                        </li>  {% endcomment %}
                        {% comment %} <li class="sidebar-item"> 
                            <a href="{% url 'user:view_emp_profile_admin' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2" ></i> 
                                <span class="topic">view Employee Profile</span> 
                            </a> 
                        </li>  {% endcomment %}
                    </ul> 
                </li> 
            </ul>
            
            <hr>
            
        </div>

        <div id="content" class="col">
            <div class="top-bar" >
             <h7>GMS System</h7>
             <p>(Grievances management system)</p>
            </div>
            <div class="bar"><span> </span></div> 
                    {% block content %}

                    <!---Dynamic Nav Content -->     
                    {% endblock %}           
                </div>
            </div>
        </div>
    </div>
    <!--search bar table cdn script-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <!--Bootstrap javascript cnd-->

    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
        
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <!--internal js-->
    <script type="text/javascript" src="{% static '/js/my.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!--jquery cnd-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</body>
</html>