GMS_proj/GMS_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import google_auth_callback
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('backoffice/', include("backoffice.urls")),
    # path('oauth2/', include('oauth2_provider_app.urls', namespace='oauth2_provider_app')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GMS_proj/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path('', views.index, name='index'),
    path('view_all_complaint_admin/', views.view_all_complaint_admin, name='view_all_complaint_admin'),
    path('login/', views.login_page, name='login'),
    path('view_complaint_reply_user/', views.view_complaint_reply_user, name='view_complaint_reply_user'),
    path('emp_profile_admin/', views.emp_profile_admin, name='emp_profile_admin'),
    path('view_emp_profile_admin/', views.view_emp_profile_admin, name='view_emp_profile_admin'),
    path('specific_complaint/', views.specific_complaint, name='specific_complaint'),
    path('complaint_user/', views.complaint_user, name='complaint_user'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
]

GMS_proj/backoffice/urls.py
app_name = 'backoffice'
from django.contrib import admin
from django.urls import path
from backoffice import views
from backoffice.views import oauth_gmail_login, oauth_callback
# from user import views as user_views
urlpatterns = [
    path('', views.navigation_admin, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('admin_registration/', views.admin_registration, name='admin_registration'),
    path('profile/', views.profile, name='profile'),
    path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    path('oauth/callback/', oauth_callback, name='oauth_callback'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('login/',views.login_page, name='login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('delete_employee', views.delete_employee, name='delete_employee'),
    # path('test/', views.test, name='test'),
    path('edit/',views.update, name='update'),
    path('complaints',views.create_complaint, name='create_complaint'),
    path('add',views.employee_add, name='employee_add'),
    
    
    
]

GMS_proj/user/urls.py
app_name = 'user'
from django.contrib import admin
from django.urls import path
from user import views
from user.views import google_auth, google_auth_callback
# from user.views import oauth_gmail_login, oauth_callback
urlpatterns = [
    path('', views.navigation, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('login/', views.login, name='login'),
    # path('change_password',views.change_password,name='change_password'),
    path('registration_user/', views.registration_user, name='registration_user'),
    #Authentication login
    # path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    
    path('edit/',views.edit_profile, name='update'),
    # path('google_login/',views.login_with_google, name='login_with_google'),
    # path('complete/gmail_login/', views.custom_login, name='complete'),
    # path('gmail/', views.login_with_gmail, name='login_with_gmail'),
    
    
    
    path('auth/google/', google_auth, name='google_auth'),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
    
]



# https://accounts.google.com/o/oauth2/auth?client_id=121742523439-s30kcv1je7lg798uen7rd4ntk1oagh39.apps.googleusercontent.com&redirect_uri=http://127.0.0.1:8000/user/complete/gmail_login/&state=PgNlIlTgE1FkGxspG8ZLTbybjrJC1H5V&response_type=code&scope=openid+email+profile

GMS_proj/backoffice/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from textblob import TextBlob
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.hashers import make_password,check_password
from shared_model.models import Profile
from backoffice.middleware import auth_b, login_checker_b
from shared_model.models import Profile
from shared_model.models import ComplaintMessage
from shared_model.models import CreateComplaint
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth.models import User
from social_django.models import UserSocialAuth
from django.utils import timezone
from datetime import datetime
from pytz import timezone as pytz_timezone
from django.utils.timezone import activate
# from django.contrib.auth.decorators import login_required
@auth_b
def profile(request):
    profile_id = request.session.get('profile_id')
    if profile_id is not None:
                print("Working id is", profile_id)
                profile = get_object_or_404(Profile, id=profile_id)
                return render(request, 'profile.html', {'profile': profile})
    else:
         print("Not working")
@login_checker_b
def oauth_gmail_login(request):
    # Redirect to Gmail authentication
    return redirect('social:begin', 'google-oauth2')

@login_checker_b
def oauth_callback(request):
    print("hello")
    print(request.method)
    return redirect('backoffice:dashboard')


# def get_user_email(request):
#     # Check if the user is authenticated
#     if request.user.is_authenticated:
#         # Retrieve the user's social authentication details
#         try:
#             user_social_auth = request.user.social_auth.get(provider='google-oauth2')
#             # Access the email address from the user's social authentication details
#             user_email = user_social_auth.extra_data.get('email')
#             if user_email:
#                 return user_email
#             else:
#                 # Handle the case where email is not available in social authentication details
#                 return None
#         except UserSocialAuth.DoesNotExist:
#             # Handle the case where the user is not authenticated via Google OAuth2
#             return None
#     else:
#         # Handle the case where the user is not authenticated
#         return None

# def logout_view(request):
#     # Clear session data
#     request.session.clear()
#     # Redirect to the login page or any other desired page
#     return redirect('login') 
@auth_b
def navigation_admin(request):
    return render(request, 'backoffice/navigation_admin.html')


@auth_b
def dashboard(request):
    User = Profile.objects.all()
    complaint = CreateComplaint.objects.all()
    create_complaint = CreateComplaint.objects.all()
    # print(get_user_email(request))
    return render(request, 'backoffice/dashboard.html', {'user': User, 'complaints': complaint,'create_complaint':create_complaint})
@auth_b
def create_complaint(request):
    create_complaint = CreateComplaint.objects.all()
    return render(request, 'backoffice/create_complaint.html',{'create_complaint':create_complaint})

     
def employee_add(request):
        if request.method == 'POST':

            name = request.POST.get('name','')
            mobile = request.POST.get('mobile','')
            email = request.POST.get('email','')
            password = request.POST.get('password','')
            confirm_password = request.POST.get('confirm_password','')
          

            error_msg = []

            response_data = {
                'status':'',
                'message':[],
                'data':''
            }
            

            if name == '':
                error_msg.append('Field Name cannot be Empty.')
            if email == '':
                error_msg.append('Field Email cannot be Empty.')
            if mobile == '':
                error_msg.append('Field Mobile Number cannot be Empty.')
            if password == '':
                error_msg.append('Field Password cannot be Empty.')
            if confirm_password == '':
                error_msg.append('Field Confirm Password cannot be Empty.')

            try:
                validate_email(email)
            except ValidationError as e:
                error_msg.append('Invalid Email Provided')
            else:
                pass

            if len(mobile) != 10:
                error_msg.append('Mobile number must be 10 character in length.')

            if password != confirm_password:
                error_msg.append('Password donot match confirm password.') 

            if Profile.objects.filter(email=email).exists():
                    error_msg.append('Email already exists. Please use a different email address.')
                    
            if(len(error_msg) == 0):
                response_data['status'] = 'success'
                response_data['message'] = ['Employee Registered Successfully.']
                response_data['data'] = []
                hashed_password=make_password(password)
                # If the email doesn't exist, create a new Profile object
                user = Profile.objects.create(name=name, mobile=mobile, email=email, password=hashed_password)
            else:
                response_data['status'] = 'error'
                response_data['message'] = error_msg
                response_data['data'] = request.POST
            

            return render(request,'backoffice/employee_add.html',response_data)
        else:
            return render(request, 'backoffice/employee_add.html')

@auth_b
def profile(request):
    return render(request, 'backoffice/profile.html')
@login_checker_b   
def forgot_password(request):
    return render(request, 'backoffice/forgot_password.html')

@login_checker_b
def login_page(request ,response_data=None):
            response_data = {
                'status': '',
                'message': [],
                'data': '',
            }

            if request.method == 'POST':
                email = request.POST.get('email')
                password = request.POST.get('password')
                try:
                    user = Profile.objects.get(email=email)
                    if Profile.objects.filter(email=email).exists() and check_password(password, user.password) and (user.profile_type == "Complaint handler(Staff)" or user.profile_type=="Admin"):
                        request.session['is_logged_in'] = True
                        request.session['email_id'] = user.email
                        request.session['profile_id'] = user.id
                        request.session['name'] = user.name
                        request.session['profile_type_id'] = user.profile_type_id
                        # Check if the provided password matches the hashed password
                        # Both email exists and password matches, redirect to dashboard
                        return redirect("backoffice:dashboard") 
                    else:
                        # User with given email doesn't exist
                        request.session['is_logged_in'] = False
                        response_data['status'] = 'error'
                        response_data['message'] = ['Invalid Credentials Provided']
                        
                except Profile.DoesNotExist:
                    request.session['is_logged_in'] = False
                    response_data['status'] = 'error'
                    response_data['message'] = ['Invalid Credentials Provided']
                    # response_data['data'] = request.POST
            return render(request, 'backoffice/login.html', response_data)
@auth_b
def logout_view(request):
            # Clear session data
            request.session.clear()
            # Redirect to the login page or any other desired page
            return render(request,'backoffice/login.html') 
@login_checker_b
def admin_registration(request):
        if request.method == 'POST':

            name = request.POST.get('name','')
            mobile = request.POST.get('mobile','')
            email = request.POST.get('email','')
            password = request.POST.get('password','')
            confirm_password = request.POST.get('confirm_password','')
          

            error_msg = []

            response_data = {
                'status':'',
                'message':[],
                'data':''
            }
            

            if name == '':
                error_msg.append('Field Name cannot be Empty.')
            if email == '':
                error_msg.append('Field Email cannot be Empty.')
            if mobile == '':
                error_msg.append('Field Mobile Number cannot be Empty.')
            if password == '':
                error_msg.append('Field Password cannot be Empty.')
            if confirm_password == '':
                error_msg.append('Field Confirm Password cannot be Empty.')

            try:
                validate_email(email)
            except ValidationError as e:
                error_msg.append('Invalid Email Provided')
            else:
                pass

            if len(mobile) != 10:
                error_msg.append('Mobile number must be 10 character in length.')

            if password != confirm_password:
                error_msg.append('Password donot match confirm password.') 

            if Profile.objects.filter(email=email).exists():
                    error_msg.append('Email already exists. Please use a different email address.')
                    
            if(len(error_msg) == 0):
                response_data['status'] = 'success'
                response_data['message'] = ['Employee Registered Successfully.']
                response_data['data'] = []
                hashed_password=make_password(password)

GMS_proj/backoffice/templates/navigation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responsive Layout</title>
 
    <!--Bootstrap css cnd-------->
    <link type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--fontawsome----------->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!--Bootstrap javascript cnd--------->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    
    <!---Search Table cdn-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css" rel="stylesheet">
    
    <!--css-->
    <link rel="stylesheet" type="text/css" href="{% static '/css/my_style.css' %}">
</head>
<body>
    <h1>backoffice</h1>
    <div class="container-fluid p-0 d-flex h-100">
        <div id="bdSidebar"
            class="d-flex flex-column flex-shrink-0 p-3 bg-success text-white offcanvas-md offcanvas-start">
            <a href="#" class="navbar-brand">Users</a>
            <hr>
            <ul class="mynav nav nav-pills flex-column mb-auto">
                <li class="nav-item mb-1">
                    <a href="{% url 'backoffice:backoffice' operation='dashboard' %}">
                        <i class="fa-regular fa-newspaper"></i>
                        Dashboard
                    </a>
                </li>
                <li class="nav-item  mb-1">
                    <a href="{% url 'user:user_registration' %}">
                        <i class="fa-regular fa-user"></i>
                        User Registration
                        <span class="notification-badge"></span>
                    </a>
                </li>
               {{request.session.is_logged_in}} 
         
                <li class="sidebar-item"> 
                    <a href="{% url 'user:complaint_user' %}" class="sidebar-link"> 
                        <i class="fas fa-sign-out-alt pe-2"></i> 
                        <span class="topic">Create Complaint</span> 
                    </a> 
                </li> 
                <li class="sidebar-item"> 
                    <a href="{% url 'user:view_all_complaint_admin' %}" class="sidebar-link"> 
                        <i class="fas fa-sign-out-alt pe-2"></i> 
                        <span class="topic">View All Complaints</span> 
                    </a> 
                <!--Admin Section---------------------->
                <hr>
                {% comment %} <li class="nav-item mb-1"> 
                    <a href="#"
                    class="sidebar-link collapsed"
                    data-bs-toggle="collapse"
                    data-bs-target="#settings"
                    aria-expanded="false"
                    aria-controls="settings"> 
                        <i class="fas fa-cog pe-2"></i> 
                        <span class="topic">Admin </span> 
                    </a> 
                </li> {% endcomment %}
                    <ul id="settings"
                        class="sidebar-dropdown list-unstyled collapse"
                        data-bs-parent="#sidebar"> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:login' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-in-alt pe-2"></i> 
                                <span class="topic">Login</span> 
                            </a> 
                        </li> 
                   
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="#" class="sidebar-link"> 
                                <i class="fas fa-user-plus pe-2"></i> 
                                <span class="topic">Register</span> 
                            </a> 
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:profile' %}" class="sidebar-link" > 
                                <i class="fas fa-sign-out-alt pe-2" ></i> 
                                <span class="topic">Profile</span> 
                            </a> 
                        </li> 
                       
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:specific_complaint' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Specific Complaint</span> 
                            </a> 
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:view_complaint_reply_user' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Complaint Reply</span> 
                            </a> 
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:emp_profile_admin' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2"></i> 
                                <span class="topic">Employee</span> 
                            </a> 
                        </li> 
                        <li class="sidebar-item"> 
                            <a href="{% url 'user:view_emp_profile_admin' %}" class="sidebar-link"> 
                                <i class="fas fa-sign-out-alt pe-2" ></i> 
                                <span class="topic">view Employee Profile</span> 
                            </a> 
                        </li> 
                    </ul> 
                </li> 
            </ul>
            
            <hr>
            <!--Bottom nav-->
            <div  class="mynav nav text-white ">
                
                {% if request.session.is_logged_in  %}

            <ul class="mynav nav nav-pills flex-column mb-auto">
                 <li class="nav-item  mb-1">
                    <a href="{% url 'user:logout_view' %}">
                        <i class="fa-regular fa-bookmark"></i>
                       Logout
                       
                    </a>
                </li> 
            </ul>
                
                {% else %} 
                
            <ul class="mynav nav nav-pills flex-column mb-auto">
                <li class="nav-item  mb-1">
                    <a href="{% url 'user:login' %}">
                        <i class="fa-regular fa-bookmark"></i>
                        Login
                        <span class="notification-badge"></span>
                    </a>
                </li>
            </ul>
     {% endif %} 
            </div>

        </div>

        <div class="bg-light flex-fill">
            <div class="p-2 d-md-none d-flex text-white bg-success">
                <a href="#" class="text-white" data-bs-toggle="offcanvas" data-bs-target="#bdSidebar">
                    <i class="fa-solid fa-bars"></i>
                </a>
                <span class="ms-3">GMS System Admin</span>
            </div>
            <div class="p-4">
                <h3>GMS System</h3>
                <hr>
                <div id="content" class="col">
                    {% block content %}

                    <!---Dynamic Nav Content -->     
                    {% endblock %}           
                </div>
            </div>
        </div>
    </div>
    <!--search bar table cdn script-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <!--Bootstrap javascript cnd-->

    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
        
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
    <!--internal js-->
    <script type="text/javascript" src="{% static '/js/my.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!--jquery cnd-->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</body>
</html>