GMS_proj/GMS_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from user.views import google_auth_callback
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('user/', include("user.urls")),
    path('backoffice/', include("backoffice.urls")),
    # path('oauth2/', include('oauth2_provider_app.urls', namespace='oauth2_provider_app')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GMS_proj/app/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path('', views.index, name='index'),
    path('view_all_complaint_admin/', views.view_all_complaint_admin, name='view_all_complaint_admin'),
    path('login/', views.login_page, name='login'),
    path('view_complaint_reply_user/', views.view_complaint_reply_user, name='view_complaint_reply_user'),
    path('emp_profile_admin/', views.emp_profile_admin, name='emp_profile_admin'),
    path('view_emp_profile_admin/', views.view_emp_profile_admin, name='view_emp_profile_admin'),
    path('specific_complaint/', views.specific_complaint, name='specific_complaint'),
    path('complaint_user/', views.complaint_user, name='complaint_user'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
]

GMS_proj/backoffice/urls.py
app_name = 'backoffice'
from django.contrib import admin
from django.urls import path
from backoffice import views
from backoffice.views import oauth_gmail_login, oauth_callback
# from user import views as user_views
urlpatterns = [
    path('', views.navigation_admin, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('admin_registration/', views.admin_registration, name='admin_registration'),
    path('profile/', views.profile, name='profile'),
    path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    path('oauth/callback/', oauth_callback, name='oauth_callback'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('login/',views.login_page, name='login'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('delete_employee', views.delete_employee, name='delete_employee'),
    # path('test/', views.test, name='test'),
    path('edit/',views.update, name='update'),
    path('complaints',views.create_complaint, name='create_complaint'),
    path('add',views.employee_add, name='employee_add'),
    
    
    
]

GMS_proj/user/urls.py
app_name = 'user'
from django.contrib import admin
from django.urls import path
from user import views
from user.views import google_auth, google_auth_callback
# from user.views import oauth_gmail_login, oauth_callback
urlpatterns = [
    path('', views.navigation, name='navigation'),
    path('complaint/<str:operation>/', views.complaint, name='complaints'),
    path('profile/', views.profile, name='profile'),
    path('forgot_password/',views.forgot_password, name='forgot_password'),
    path('dashboard/',views.dashboard, name='dashboard'),
    path('logout_view/',views.logout_view, name='logout_view'),
    path('login/', views.login, name='login'),
    # path('change_password',views.change_password,name='change_password'),
    path('registration_user/', views.registration_user, name='registration_user'),
    #Authentication login
    # path('oauth/gmail/', oauth_gmail_login, name='oauth_gmail_login'),
    
    path('edit/',views.edit_profile, name='update'),
    # path('google_login/',views.login_with_google, name='login_with_google'),
    # path('complete/gmail_login/', views.custom_login, name='complete'),
    # path('gmail/', views.login_with_gmail, name='login_with_gmail'),
    
    
    
    path('auth/google/', google_auth, name='google_auth'),
    path('auth/google/callback/', google_auth_callback, name='google_auth_callback'),
    
]



# https://accounts.google.com/o/oauth2/auth?client_id=121742523439-s30kcv1je7lg798uen7rd4ntk1oagh39.apps.googleusercontent.com&redirect_uri=http://127.0.0.1:8000/user/complete/gmail_login/&state=PgNlIlTgE1FkGxspG8ZLTbybjrJC1H5V&response_type=code&scope=openid+email+profile

GMS_proj/backoffice/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from textblob import TextBlob
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.contrib.auth.hashers import make_password,check_password
from shared_model.models import Profile
from backoffice.middleware import auth_b, login_checker_b
from shared_model.models import Profile
from shared_model.models import ComplaintMessage
from shared_model.models import CreateComplaint
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth.models import User
from social_django.models import UserSocialAuth
from django.utils import timezone
from datetime import datetime
from pytz import timezone as pytz_timezone
from django.utils.timezone import activate
# from django.contrib.auth.decorators import login_required
@auth_b
def profile(request):
    profile_id = request.session.get('profile_id')
    if profile_id is not None:
                print("Working id is", profile_id)
                profile = get_object_or_404(Profile, id=profile_id)
                return render(request, 'profile.html', {'profile': profile})
    else:
         print("Not working")
@login_checker_b
def oauth_gmail_login(request):
    # Redirect to Gmail authentication
    return redirect('social:begin', 'google-oauth2')

@login_checker_b
def oauth_callback(request):
    print("hello")
    print(request.method)
    return redirect('backoffice:dashboard')


# def get_user_email(request):
#     # Check if the user is authenticated
#     if request.user.is_authenticated:
#         # Retrieve the user's social authentication details
#         try:
#             user_social_auth = request.user.social_auth.get(provider='google-oauth2')
#             # Access the email address from the user's social authentication details
#             user_email = user_social_auth.extra_data.get('email')
#             if user_email:
#                 return user_email
#             else:
#                 # Handle the case where email is not available in social authentication details
#                 return None
#         except UserSocialAuth.DoesNotExist:
#             # Handle the case where the user is not authenticated via Google OAuth2
#             return None
#     else:
#         # Handle the case where the user is not authenticated
#         return None

# def logout_view(request):
#     # Clear session data
#     request.session.clear()
#     # Redirect to the login page or any other desired page
#     return redirect('login') 
@auth_b
def navigation_admin(request):
    return render(request, 'backoffice/navigation_admin.html')


@auth_b
def dashboard(request):
    User = Profile.objects.all()
    complaint = CreateComplaint.objects.all()
    create_complaint = CreateComplaint.objects.all()
    # print(get_user_email(request))
    return render(request, 'backoffice/dashboard.html', {'user': User, 'complaints': complaint,'create_complaint':create_complaint})
@auth_b
def create_complaint(request):
    create_complaint = CreateComplaint.objects.all()
    return render(request, 'backoffice/create_complaint.html',{'create_complaint':create_complaint})

     
def employee_add(request):
        if request.method == 'POST':

            name = request.POST.get('name','')
            mobile = request.POST.get('mobile','')
            email = request.POST.get('email','')
            password = request.POST.get('password','')
            confirm_password = request.POST.get('confirm_password','')
          

            error_msg = []

            response_data = {
                'status':'',
                'message':[],
                'data':''
            }
            

            if name == '':
                error_msg.append('Field Name cannot be Empty.')
            if email == '':
                error_msg.append('Field Email cannot be Empty.')
            if mobile == '':
                error_msg.append('Field Mobile Number cannot be Empty.')
            if password == '':
                error_msg.append('Field Password cannot be Empty.')
            if confirm_password == '':
                error_msg.append('Field Confirm Password cannot be Empty.')

            try:
                validate_email(email)
            except ValidationError as e:
                error_msg.append('Invalid Email Provided')
            else:
                pass

            if len(mobile) != 10:
                error_msg.append('Mobile number must be 10 character in length.')

            if password != confirm_password:
                error_msg.append('Password donot match confirm password.') 

            if Profile.objects.filter(email=email).exists():
                    error_msg.append('Email already exists. Please use a different email address.')
                    
            if(len(error_msg) == 0):
                response_data['status'] = 'success'
                response_data['message'] = ['Employee Registered Successfully.']
                response_data['data'] = []
                hashed_password=make_password(password)
                # If the email doesn't exist, create a new Profile object
                user = Profile.objects.create(name=name, mobile=mobile, email=email, password=hashed_password)
            else:
                response_data['status'] = 'error'
                response_data['message'] = error_msg
                response_data['data'] = request.POST
            

            return render(request,'backoffice/employee_add.html',response_data)
        else:
            return render(request, 'backoffice/employee_add.html')

@auth_b
def profile(request):
    return render(request, 'backoffice/profile.html')
@login_checker_b   
def forgot_password(request):
    return render(request, 'backoffice/forgot_password.html')

@login_checker_b
def login_page(request ,response_data=None):
            response_data = {
                'status': '',
                'message': [],
                'data': '',
            }

            if request.method == 'POST':
                email = request.POST.get('email')
                password = request.POST.get('password')
                try:
                    user = Profile.objects.get(email=email)
                    if Profile.objects.filter(email=email).exists() and check_password(password, user.password) and (user.profile_type == "Complaint handler(Staff)" or user.profile_type=="Admin"):
                        request.session['is_logged_in'] = True
                        request.session['email_id'] = user.email
                        request.session['profile_id'] = user.id
                        request.session['name'] = user.name
                        request.session['profile_type_id'] = user.profile_type_id
                        # Check if the provided password matches the hashed password
                        # Both email exists and password matches, redirect to dashboard
                        return redirect("backoffice:dashboard") 
                    else:
                        # User with given email doesn't exist
                        request.session['is_logged_in'] = False
                        response_data['status'] = 'error'
                        response_data['message'] = ['Invalid Credentials Provided']
                        
                except Profile.DoesNotExist:
                    request.session['is_logged_in'] = False
                    response_data['status'] = 'error'
                    response_data['message'] = ['Invalid Credentials Provided']
                    # response_data['data'] = request.POST
            return render(request, 'backoffice/login.html', response_data)
@auth_b
def logout_view(request):
            # Clear session data
            request.session.clear()
            # Redirect to the login page or any other desired page
            return render(request,'backoffice/login.html') 
@login_checker_b
def admin_registration(request):
        if request.method == 'POST':

            name = request.POST.get('name','')
            mobile = request.POST.get('mobile','')
            email = request.POST.get('email','')
            password = request.POST.get('password','')
            confirm_password = request.POST.get('confirm_password','')
          

            error_msg = []

            response_data = {
                'status':'',
                'message':[],
                'data':''
            }
            

            if name == '':
                error_msg.append('Field Name cannot be Empty.')
            if email == '':
                error_msg.append('Field Email cannot be Empty.')
            if mobile == '':
                error_msg.append('Field Mobile Number cannot be Empty.')
            if password == '':
                error_msg.append('Field Password cannot be Empty.')
            if confirm_password == '':
                error_msg.append('Field Confirm Password cannot be Empty.')

            try:
                validate_email(email)
            except ValidationError as e:
                error_msg.append('Invalid Email Provided')
            else:
                pass

            if len(mobile) != 10:
                error_msg.append('Mobile number must be 10 character in length.')

            if password != confirm_password:
                error_msg.append('Password donot match confirm password.') 

            if Profile.objects.filter(email=email).exists():
                    error_msg.append('Email already exists. Please use a different email address.')
                    
            if(len(error_msg) == 0):
                response_data['status'] = 'success'
                response_data['message'] = ['Employee Registered Successfully.']
                response_data['data'] = []
                hashed_password=make_password(password)

GMS_proj/backoffice/templates/backoffice/chat.html
{% extends 'backoffice/navigation_admin.html' %}
   {% block content %}
    {% load static %}
    {% for chat in chats %}
    
    {%if chat.profile.profile_type_id == 1 %}
            <div class="card bg-info">

    {% else %}
        <div class="card bg-warning">
        {% endif %}


        <div class="card-body">
          <h5><b>{{chat.profile.name}}</b></h5>
          <p>{{chat.message}}</p>
          <p class="msg-time">{{chat.created_at}}</p>
        </div>
      </div>

      {% endfor %}
    

    {% endblock %} 

GMS_proj/backoffice/templates/backoffice/complaint_list.html
{% extends 'backoffice/navigation_admin.html' %}
   {% block content %}
    {% load static %}
   

<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center">Complaints List</h1>
    <div class="col-md-10">
        <div class="table-wrapper">
      <table id="example" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th scope="col"style="width:10vw;">S No</th>
            <th scope="col"style="width:15vw;">Name</th>
            <th scope="col"style="width:10vw;">Phone No</th>
            <th scope="col" style="width:40vw; text-align: center;">Current Handler</th>
            <th scope="col"style="width:10vw;">created_at</th>
            <th scope="col"style="width:10vw;">updated_at</th>
            <th scope="col"style="width:10vw;">Sentiment</th>
            <th scope="col"style="width:10vw;">Actions</th>
          </tr>
        </thead>
        {% for  complaint in complaints %}
        <tr>
          <td>{{forloop.counter}}</td>
          <td>{{complaint.profile.name}}</td>
          <td>{{complaint.profile.mobile}}</td>
          <td>{{complaint.current_handler}}</td>
          <td>{{complaint.created_at}}</td>
          <td>{{complaint.updated_at}}</td>
          <td>{{complaint.sentiment}}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn btn-primary" onclick="showProfile1({{ complaint.id }})" >
                <i class="far fa-eye"></i>
              </button>

              <div class="btn-group" role="group" aria-label="Basic example">
                <button type="button" class="btn btn-success" onclick="showComplaint({{ complaint.id }})" >
                  <i class="fa-solid fa-reply"></i>
                </button>

              <button type="button" class="btn btn-danger" onclick="deleteProfile({{ complaint.profile.id }})"><i class="far fa-trash-alt"></i></button>
            </div>
          </td>
         
        </tr>
        {% endfor %}
      </table>
    </div>

                </div>
            </div>
        </div>
    </div>
    <script>
      function showProfile1(complaint_id) {
          // Redirect to the detail page with employeeId
          window.location.href = "{% url 'backoffice:complaints' operation='view' %}?id=" + complaint_id;
      }
      function showComplaint(complaint_id) {
        // Redirect to the detail page with employeeId
        window.location.href = "{% url 'backoffice:complaints' operation='message' %}?id=" + complaint_id;
    }
    function deleteProfile(complaint_id) {
      // Redirect to the detail page with employeeId
      window.location.href = "{% url 'backoffice:complaints' operation='delete' %}";
  }
  </script>
 {% endblock %}

GMS_proj/backoffice/templates/backoffice/dashboard.html
{% extends 'backoffice/navigation_admin.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="dashboard-heading">
        <div>
           <h1>Dashboad </h1> 
        </div>
        <div class="right"><h4>Hello: {{ request.session.name }} </div>
        
   </div>
   <hr>

<a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'user:navigation' %}">
    <div class="sidebar-brand-icon rotate-n-15"></div>
</a>

<div class="container-dashboard-admin">
  <div class="row">
    <div class="col-md-4">
    <div class="box" id="employee-box1">
        <i class="fa-regular fa-user"></i>
        <h2>Total Employee &nbsp;</h2>

        <h1>{{ user|length }}</h1>
    </div>
  </div>
  <div class="col-md-4">
    <div class="box" id="employee-box2">
        <i class="fa-regular fa-address-book"></i>
        <h2>Total Complaints </h2>
        <h1>{{ complaints|length }}</h1>
    </div>
  </div>

    <div class="col-md-4">
     <div class="box" id="employee-box3">
        <i class="fa-regular fa-circle-check"></i>
        <h2>Active Acc &nbsp;</h2>
        <h1>{{ complaints|length }}</h1>
     </div>
    </div>

</div>
</div>
</div>
</div>


<script>
    // Get the box elements
    const employeeBox1 = document.getElementById('employee-box1');
    const employeeBox2 = document.getElementById('employee-box2');
    const employeeBox3 = document.getElementById('employee-box3');

    // Add click event listeners to the boxes
    employeeBox1.addEventListener('click', function() {
        // Redirect to the specified URL when the box is clicked
        window.location.href = "{% url 'backoffice:complaints' operation='employee_list' %}";
    });

    employeeBox2.addEventListener('click', function() {
        // Redirect to the specified URL when the box is clicked
        window.location.href = "{% url 'backoffice:create_complaint' %}";
    });

    employeeBox3.addEventListener('click', function() {
        // Redirect to the specified URL when the box is clicked
        window.location.href = "{% url 'backoffice:complaints' operation='navigation' %}";
    });
</script>

{% endblock %}

GMS_proj/backoffice/templates/backoffice/employee_add.html
{% extends 'backoffice/navigation_admin.html' %}
   {% block content %}
    {% load static %}
   
<div class="container mt-5" >
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center">Employee Registration</h2><br>
          
          <form id="registration_form_id" action="{% url 'backoffice:employee_add' %}" method="post" >
          {% csrf_token %}
            <div class="mb-3">
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ data.name }}" required />
          </div>
          <div class="mb-3">
              <input type="tel" class="form-control" id="phone_no" name="mobile" placeholder = "Mobile No" value="{{ data.mobile }}" required/>
          </div>
          <div class="mb-3">
              <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ data.email }}" required>
          </div>
          <div class="mb-3 ">
            <input type="password" class="form-control" id="password"  name="password" placeholder="Password" data-toggle="tooltip" data-placement="top" title="At least a  lowercase, uppercase, number, minimum 8 character" value="{{ data.password }}" required>

          </div>
          <div class="mb-3">
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password" value="{{ data.confirm_password }}">
          </div>
          <div class="mb-3">
            <select class="form-select " id="employee_type" name="employee_type" required>
                <option value="" selected disabled>Select Employee Type</option>
                <option value="Admin">Admin</option>
                <option value="Complaint handler">Complaint Handler(Staff)</option>
            </select>
        </div>
            <button type="submit" id ="registration_button_id" class="btn btn-primary w-100">Submit</button>
            {% if request.method == 'POST'  %}
            <ul class="messages">
              {% for info in message%}
              {%if "Employee Registered Successfully." in info%}
              <li class="text-success">{{ info }}</li>
              {% else %}
              <li class="text-danger">{{ info }}</li>
              {% endif %}
              {% endfor %}
              
              {% comment %} {% if "User Registered Successfully." in error_message%}
              <li class="text-success">{{ error_message }}</li>
              {% else %}
              <li class="text-danger">{{ error_message }}</li>
              {% endif %} {% endcomment %}

            </ul>
            {% endif %}
            <hr>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

                </div>
            </div>
        </div>
    </div>
  {% endblock %}

GMS_proj/backoffice/templates/backoffice/employee_list.html
{% extends 'backoffice/navigation_admin.html' %}
   {% block content %}
    {% load static %}
  
<div class="container">
  <a href="{% url 'backoffice:employee_add' %}" class="sidebar-link">
  <button class="add-employee-btn" >
    <span class="icon">+</span> Add Employees
  </button>
</a>
  <div class="row justify-content-center">
    <h1 class="text-center">Employees </h1>
    <div class="col-md-10">
        <div class="table-wrapper">
    <table id="example" class="table table-striped table-bordered">

        <thead class="thead-dark">
          <tr>
            
            <th scope="col"style="width:10vw;">Employe Id</th>
            <th scope="col"style="width:15vw;">Name</th>
            <th scope="col"style="width:10vw;">Mobile</th>
            <th scope="col"style="width:10vw;">Email</th>
          
            <th scope="col">Actions</th>
          </tr>
        </thead>

        {% for  employee in employees %}
        <tr>
          <td>{{employee.id}}</td>
          <td>{{employee.name}}</td>
          <td>{{employee.mobile}}</td>
          <td>{{employee.email}}</td>
          <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn btn-primary" onclick="showProfile({{ employee.id }})" ><i class="far fa-eye"></i></button>
              
              <button type="button" class="btn btn-danger delete-btn"onclick="delProfile({{ employee.id }})" data-employee-id="{{ employee.id }}"><i class="far fa-trash-alt"></i></button>
      </div>
          </td>
         
        </tr>
        {% endfor %}
       
     </div>
                </div>
            </div>
        </div>
    </div>
    <script>
      function delProfile(employeeId) {
          // Redirect to the detail page with employeeId
          window.location.href = "{% url 'backoffice:delete_employee'%}?id="+employeeId;
      }

{% comment %}       
      // delete Profile-----------------------------------------------------------

        // Get CSRF token from meta tag
        const csrfToken = document.querySelector('[name=csrf-token]').getAttribute('content');
    
        // Wait for the DOM to be ready
        document.addEventListener("DOMContentLoaded", function() {
            // Select all delete buttons
            const deleteButtons = document.querySelectorAll('.delete-btn');
    
            // Loop through each delete button and attach event listener
            deleteButtons.forEach(function(button) {
                button.addEventListener('click', function() {
                    // Get the employee ID from the data attribute
                    const employeeId = this.getAttribute('data-employee-id');
    
                    // Confirm deletion
                    if (confirm('Are you sure you want to delete this employee?')) {
                        // Send AJAX request to delete employee
                        fetch(`/backoffice/backoffice/delete-employee/${employeeId}/`, {
                            method: 'POST',
                            headers: {
                                'Content-Type': 'application/json',
                                'X-CSRFToken': csrfToken // Include CSRF token in headers
                            },
                            
                        })
                        .then(function(response) { return response.json(); })
                        .then(function(json) {
                           if(json.status == 'success'){
                            this.closest('tr').remove();
                            alert(json.message)
                           }else{
                            alert(json.message)
                           }
                             
                          
                        });
                    }
                });
            });
        }); {% endcomment %}
  </script>
   {% endblock %}

GMS_proj/backoffice/templates/backoffice/forgot_password.html
{% extends 'backoffice/navigation_admin.html' %}

{% block content %}
    {% load static %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="display-6 text-center mb-4">Forgot Password</h2>
                        <form class="row g-3 needs-validation" novalidate>
                            <div class="mb-3">
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email" required>
                                <div class="invalid-feedback">
                                    Please enter a valid email address.
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary w-100">Reset Password</button>
                        </form>
                    </div>
                </div>
            </div>
            <p class="text-center">Remembered your password? <a href="{% url 'backoffice:login' %}" class="text-primary">Login</a></p>
           
        </div>
    </div>
{% endblock %}

GMS_proj/backoffice/templates/backoffice/registration.html
{% extends 'backoffice/navigation_admin.html' %}
   {% block content %}
    {% load static %}
   
<div class="container mt-5" >
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-center">Employee Registration</h2><br>
          
          <form id="registration_form_id" action="{% url 'backoffice:admin_registration' %}" method="post" >
          {% csrf_token %}
            <div class="mb-3">
              <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="{{ data.name }}" required />
          </div>
          <div class="mb-3">
              <input type="tel" class="form-control" id="phone_no" name="mobile" placeholder = "Mobile No" value="{{ data.mobile }}" required/>
          </div>
          <div class="mb-3">
              <input type="email" class="form-control" id="email" name="email" placeholder="Email" value="{{ data.email }}" required>
          </div>
          <div class="mb-3 ">
            <input type="password" class="form-control" id="password"  name="password" placeholder="Password" data-toggle="tooltip" data-placement="top" title="At least a  lowercase, uppercase, number, minimum 8 character" value="{{ data.password }}" required>

          </div>
          <div class="mb-3">
              <input type="password" class="form-control" id="confirm_password" name="confirm_password" placeholder="Confirm Password" value="{{ data.confirm_password }}">
          </div>
          <div class="mb-3">
            <select class="form-select " id="employee_type" name="employee_type" required>
                <option value="" selected disabled>Select Employee Type</option>
                <option value="Admin">Admin</option>
                <option value="Complain handler">Complain Handler(Staff)</option>
            </select>
        </div>
            <button type="submit" id ="registration_button_id" class="btn btn-primary w-100">Submit</button>
            {% if request.method == 'POST'  %}
            <ul class="messages">
              {% for info in message%}
              {%if "User Registered Successfully." in info%}
              <li class="text-success">{{ info }}</li>
              {% else %}
              <li class="text-danger">{{ info }}</li>
              {% endif %}
              {% endfor %}
              
              {% comment %} {% if "User Registered Successfully." in error_message%}
              <li class="text-success">{{ error_message }}</li>
              {% else %}
              <li class="text-danger">{{ error_message }}</li>
              {% endif %} {% endcomment %}

            </ul>
            {% endif %}
            <hr>
            <p class="text-center"> Already have an account? <a href="{%url 'user:login' %}">Login</a></p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

                </div>
            </div>
        </div>
    </div>
  {% endblock %}